### ISSUE TITLE
Environment Setup Guide

### ISSUE THREAD

**Issue by mcristina422** [carlosedp/riscv-bringup#1]
I'd love to help contribute to getting containers and Go applications on Risc-V. I think it would be helpful if you documented here how you got your current environment setup for working on this.

Personally, I just ordered a [hifive1-rev-b](https://www.sifive.com/boards/hifive1-rev-b) and just began to see if I can use qemu to start running tests now.

**Comment by carlosedp** [comment]
Hi Michael, this is an important part to get more people collaborating. I currently build everything on a SiFive Unleashed but you might be able to do all tests soon on Qemu when a bug on thread sync and atomics gets fixed soon with a [patch](http://lists.nongnu.org/archive/html/qemu-riscv/2019-05/msg00134.html) posted on their mailing list.

I already have a Qemu image and script setup just in need of cleanup and packaging. I might make this available in some days for download.

Regarding the HiFive1, It's a riscv32 and doesn't run Linux.

**Comment by carlosedp** [comment]
Michael, check this out: https://github.com/carlosedp/riscv-bringup/blob/master/Qemu-VM.md
Can you test it and report back?

**Comment by marcopeereboom** [comment]
needs to be updated but still accurate https://github.com/marcopeereboom/riscv-bringup-doco

**Comment by carlosedp** [comment]
That's some nice info @marcopeereboom! I will link to it here in the readme.

I was working on a section on building Go that I just pushed.

Check it out @mcristina422: https://github.com/carlosedp/riscv-bringup#building-go-on-your-risc-v-vm-or-sbc

**Comment by mcristina422** [comment]
Awesome resources! Definitely everything I've needed, so feel free to close
