### ISSUE TITLE
Fedora link leads to "No preview available. File is in owner's trash"

### ISSUE THREAD

**Issue by tommythorn** [carlosedp/riscv-bringup#12]
Repro:
* visit https://github.com/carlosedp/riscv-bringup
* scroll down to Fedora
* click "Fedora"

It seems the Debian Sid and Ubuntu Focal links work (haven't tested them recently)

**Comment by carlosedp** [comment]
Since Fedora folks have been providing the images, I've removed mine. Will take it off the readme.

**Comment by carlosedp** [comment]
Fixed by #1de3420.

**Comment by zinovya** [comment]
@carlosedp Do you mean that Fedora risc-v now comes with docker? If so, could you please share a link where I can download it?
