### ISSUE TITLE
K3s support for Ubuntu Focal

### ISSUE THREAD

**Issue by maiquanghiep** [carlosedp/riscv-bringup#15]
When I start the K3s in the https://github.com/carlosedp/riscv-bringup/tree/master/kubernetes
The k3s service fails with the error message "Version `GLIBC_2.33' not found". Could you provide the old version 1.16 of k3s?
I'm not sure how I could update the  GLIBC_2.33 for  Ubuntu Focal

**Comment by carlosedp** [comment]
I don't have the binary for 1.16 anymore... I built it on Ubuntu Hippo.. isn't the lib the same version?

**Comment by maiquanghiep** [comment]
I'm using the  riscv64-QemuVM image which doesn't have the GLIBC_2.33.  So I try to create the Ubuntu Hippo myselft using the link https://github.com/carlosedp/riscv-bringup/blob/master/Qemu/Readme.md. But I stuck at  Generate initrd on rootfs by using chroot with error: "W: Couldn't identify type of root file system for fsck hook". I'm not sure if is there any pushd  or popd because the command is not match with the directory.
Do you have the Ubuntu Hippo Qemu?

**Comment by maiquanghiep** [comment]
GLIBC_2.33 dependency solved by using Ubuntu hirsute
