### ISSUE TITLE
Correct Unmatched patches branch?

### ISSUE THREAD

**Issue by drmpeg** [carlosedp/riscv-bringup#17]
The HiFive Unmatched guide is a little broken (although still extremely useful). The sifive/meta-sifive repository has been updated considerably and no longer matches your instructions. For example, the meta-sifive/recipes-kernel/linux/files/unmatched/ directory no longer exists.

What is the correct branch for sifive/meta-sifive to match your instructions?

**Comment by carlosedp** [comment]
Fixed by f385e48.

**Comment by drmpeg** [comment]
Thank you!

**Comment by drmpeg** [comment]
I think you need a ```pushd meta-sifive``` before:
```
lasttag=$(git describe --tags `git rev-list --tags --max-count=1`)
echo $lasttag
git checkout $lasttag
```
And ```popd``` after.

**Comment by carlosedp** [comment]
Done, pushed.
Thanks!
