### ISSUE TITLE
Unmatched image not working

### ISSUE THREAD

**Issue by kallisti5** [carlosedp/riscv-bringup#18]
The unmatched image isn't working and produces this:
```
U-Boot SPL 2021.01-dirty (Apr 09 2021 - 11:18:24 -0300)
Trying to boot from MMC1
```

I wrote the latest u-boot spl + openSBI from https://github.com/haiku/firmware/tree/master/u-boot/riscv64/unmatched to the first two partitions per https://github.com/haiku/firmware/blob/master/u-boot/docs/sifive_unmatched/README.md, however now it just hangs at:

```
U-Boot SPL 2021.07-rc4-00022-gcf066a20c3 (Jun 12 2021 - 11:24:00 -0500)
Trying to boot from MMC1


U-Boot 2021.07-rc4-00022-gcf066a20c3 (Jun 12 2021 - 11:24:00 -0500)

CPU:   rv64imafdc
Model: SiFive HiFive Unmatched A00
DRAM:  16 GiB
MMC:   spi@10050000:mmc@0: 0
Loading Environment from nowhere... OK
In:    serial@10010000
Out:   serial@10010000
Err:   serial@10010000
Model: SiFive HiFive Unmatched A00
Net:   
Error: ethernet@10090000 address not set.
No ethernet found.

Hit any key to stop autoboot:  0 
PCIE-0: Link up (Gen1-x8, Bus0)

Device 0: Vendor: 0x1987 Rev: RKT303.3 Prod: DC4E070C08D300001862
            Type: Hard Disk
            Capacity: 244198.3 MB = 238.4 GB (500118192 x 512)
... is now current device
Scanning nvme 0:1...
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
Scanning disk mmc@0.blk...
** Unrecognized filesystem type **
** Unrecognized filesystem type **
Scanning disk nvme#0.blk#0...
Found 6 disks
No EFI system partition

Error: ethernet@10090000 address not set.
BootOrder not defined
EFI boot manager: Cannot load any image
starting USB...
Bus xhci_pci: Register 4000840 NbrPorts 4
Starting the controller
USB XHCI 1.00
scanning bus xhci_pci for devices... 3 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found

Device 0: unknown device
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:3...
Found /boot/extlinux/extlinux.conf
Retrieving file: /boot/extlinux/extlinux.conf
760 bytes read in 6 ms (123 KiB/s)
SiFive Unmatched Boot Options
1:      Linux kernel-5.11.12
2:      Linux kernel-5.11.12 (recovery mode)
Enter choice: 1
1:      Linux kernel-5.11.12
Retrieving file: /boot/initrd.img-5.11.12
9285806 bytes read in 8055 ms (1.1 MiB/s)
Retrieving file: /boot/vmlinuz-5.11.12
8757026 bytes read in 7590 ms (1.1 MiB/s)
append: earlyprintk rw root=/dev/mmcblk0p3 rootfstype=ext4 rootwait console=ttySIF0,115200 LANG=en_US.UTF-8 earlycon
Retrieving file: /boot/dtbs/5.11.12/sifive/hifive-unmatched-a00.dtb
10473 bytes read in 18 ms (567.4 KiB/s)
   Uncompressing Kernel Image
Moving Image from 0x84000000 to 0x80200000, end=81349000
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Ramdisk to ff724000, end fffff0ae ... 
```

My attempt at getting Debian 11 running ended with the same hang :-|

Maybe a u-boot bug with main/master u-boot?

**Comment by carlosedp** [comment]
Probably some incompatibility between u-boot master and the patches used here in the guide.
If using the pointed-out versions it work.

**Comment by kallisti5** [comment]
That was the point, the image provided doesn't work either as-is on my HiFive Unmatched.

```
https://github.com/carlosedp/riscv-bringup/releases/download/v1.0/UbuntuHippo-RISC-V.img.gz
```

Written to a new 64GiB microSD card produces:
```
U-Boot SPL 2021.01-dirty (Apr 09 2021 - 11:18:24 -0300)
Trying to boot from MMC1
```

**Comment by kallisti5** [comment]
I tried ```SiFive-Unmatched-UbuntuFocal-RISC-V.img.zip```

and got this:
```
U-Boot SPL 2021.01-dirty (Mar 06 2021 - 09:43:28 -0500)
Trying to boot from MMC1
t0Erucled ennhandeled exceptiioslne: lIlletgal ins
0     ti0on
 8PC: 000000000008A00802000A0000 R0AV:A9000000:000000800079c TV7AL: 00000000941b0187


resetting ...
..e resosesese.gt
otsresnettsng# .e.
reeseR
      t TnoR Rsuppo#rtleds y
                            Ret
### ERRO#R ### Please RESET the board ###
```

Maybe some hardware difference between your board and the ones shipping Jun 2021?

**Comment by mikedilger** [comment]
I have the same problem with it being stuck at "Trying to boot from MMC1"

I didn't try doing it exactly as specified so I'm not saying "there's a bug!", I'm just saying that @kallisti5 isn't alone with this issue.

Admittedly I'm using master branch of u-boot which seems to have the 53 sifive-meta patches already installed (at least, most of them when attempted ask if I meant to reverse the patch, including the last one 0053).  On master, the unmatched build target is now just called "sifive_unmatched_defconfig"

I tried 'menuconfig' and turning on a bunch of things that might affect this but I haven't been able to find the magic yet.

Also the fw_dynamic.bin from opensbi was built from master as well, and again I couldn't apply the sifive-meta patches (too far out of date).

**Comment by carlosedp** [comment]
The patches apply to the specified versions of U-Boot and the Kernel. Make sure your SDCard is partitioned according to the instructions since the correct initial block for the partitions is mandatory for correct boot.

**Comment by mikedilger** [comment]
The latest commit solved my problem.  Unhijacking thread in 3.. 2.. 1..

**Comment by carlosedp** [comment]
Awesome, great to know @mikedilger!
Any news @kallisti5 ?

**Comment by Asara** [comment]
Having a very similar issue as @kallisti5 

```Device 0: unknown device
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:3...
Found /boot/extlinux/extlinux.conf
Retrieving file: /boot/extlinux/extlinux.conf
826 bytes read in 6 ms (133.8 KiB/s)
SiFive Unmatched Boot Options
1:      Linux kernel-5.12.19-dirty
2:      Linux kernel-5.12.19-dirty (recovery mode)
Enter choice: 1:        Linux kernel-5.12.19-dirty
Retrieving file: /boot/initrd.img-5.12.19-dirty
Failed to load '/boot/initrd.img-5.12.19-dirty'
Skipping kernel-5.12.19-dirty for failure retrieving initrd
2:      Linux kernel-5.12.19-dirty (recovery mode)
Retrieving file: /boot/initrd.img-5.12.19-dirty
Failed to load '/boot/initrd.img-5.12.19-dirty'
Skipping recovery-kernel-5.12.19-dirty for failure retrieving initrd
SCRIPT FAILED: continuing...
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
Scanning disk mmc@0.blk...                                                                                                                        
** Unrecognized filesystem type **
** Unrecognized filesystem type **
Scanning disk nvme#0.blk#1...
** Unrecognized filesystem type **
Found 5 disks
No EFI system partition
BootOrder not defined
EFI boot manager: Cannot load any image
ethernet@10090000: PHY present at 0
ethernet@10090000: Starting autonegotiation...
ethernet@10090000: Autonegotiation complete
ethernet@10090000: link up, 1000Mbps full-duplex (lpa: 0x3800)
BOOTP broadcast 1
DHCP client bound to address 192.168.0.86 (2 ms)
*** ERROR: `serverip' not set
Cannot autoload with TFTPGET
missing environment variable: pxeuuid
Retrieving file: /boot/extlinux/pxelinux.cfg/01-70-b3-d5-92-f4-c7
ethernet@10090000: PHY present at 0
```

This continues looping on the DHCP/ERROR blocks indefinitely afterwards.

For some background, there is an issue running `for f in ../meta-sifive/recipes-bsp/u-boot/files/unmatched/*.patch; do echo $f;patch -p1 < $f;done`

```
git checkout c4fddedc48f336eabc4ce3f74940e6aa372de18c
Note: switching to 'c4fddedc48f336eabc4ce3f74940e6aa372de18c'.
...
HEAD is now at c4fddedc48 Prepare v2021.01
asara@host:~/riscv/unmatched/u-boot$ for f in ../meta-sifive/recipes-bsp/u-boot/files/unmatched/*.patch; do echo $f;patch -p1 < $f;done 
../meta-sifive/recipes-bsp/u-boot/files/unmatched/0001-drivers-clk-sifive-fu740-prci-replace-pciaux-with-pc.patch
can't find file to patch at input line 22
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
```

So I built it with upstream u-boot 2021.07 (instead of c4fddedc48/2021.01) which contains the files being patched via meta-sifive which dumps the error at the beginning of the post.

**Comment by kallisti5** [comment]
The latest u-boot master code fixed the issue for me.   I have binaries here (the commit hash is mentioned in the README.md)
https://github.com/haiku/firmware/tree/master/u-boot/riscv64/unmatched

There's one bug left I generally encounter which I submitted a workaround for to u-boot (ensuring to run pci enum; usb start before looking for bootloaders)

**Comment by Asara** [comment]
@kallisti5 when using your binaries, the only output that shows up is: `f0??þ?ÀððÌàÀÀÀÀÀÀÀÀÀÀÀÀÀÃ`, it doesn't even seem to get into u-boot.

When I built the spl/itb myself using u-boot master, the device just loops as mentioned [above](https://github.com/carlosedp/riscv-bringup/issues/18#issuecomment-904319534).

**Comment by Asara** [comment]
Hm. I am definitely using an A1 card.

Here is what I'm running exactly. It is essentially the same as the directions provided:
https://gist.github.com/Asara/a17052f9cca8ccda6d1aa89b0f0453de
