### ISSUE TITLE
Question about upgrade to 5.12.10

### ISSUE THREAD

**Issue by soundnut** [carlosedp/riscv-bringup#19]
Hi,

I've tried to upgrade the kernel to the 5.12.10 following your instructions but keep running into issues during boot. 
RootFS is on a nvme card. The SDCard is installed and was originally flashed with the image from ubuntu.

Patching, building and packaging the kernel into debs works without hick-ups. 
During boot the system drops into initramfs and complains that there's no /dev/nvme0n1p1. I tried to load the nvme module manually with modprobe but modinfo nvme reports that /5.12.10/ is missing. My guess is that I also need to update the SDCard to reflect the new kernel/modules but I don't know how to build these parts and where they need to go. 
Can you give me a hint?

Thanks

**Comment by carlosedp** [comment]
Check if you are including the NVME driver module into initramfs so it can load the boot partition from it.

When generating the initramfs, it will look into `/etc/initramfs-tools/modules` for which modules to add.

Check: https://github.com/carlosedp/riscv-bringup/tree/master/unmatched#use-nvme-as-root-filesystem

**Comment by soundnut** [comment]
thanks - not 100% sure where I went wrong but simply adding nvme to modules didn't do the trick. (most likely my kernel config since I've tried to slim it down as I've been compiling on the unmatched)

I've rebuilt the whole setup and this did the trick. (cross compiling this time)
I now have a working 5.12.14 with rootfs on nvme.
Thanks again for your help.

**Comment by carlosedp** [comment]
Awesome, great to know!
