### ISSUE TITLE
typo in unmatched creating SDcard section

### ISSUE THREAD

**Issue by jim-wilson** [carlosedp/riscv-bringup#20]
It mentions copying fw_payload.bin to partition 2.  I think that is a editing error from the older unleashed instructions where that is probably correct because that page describes an older scheme.  The installing/updating new kernel section says to copy u-boot.itb to partition 2 which looks like the correct solution.

From
[https://forums.sifive.com/t/installing-gentoo-on-the-unmatched/4835/8](url)

**Comment by carlosedp** [comment]
Fixed! Thanks Jim!
