### ISSUE TITLE
suggest specify meta-sifive branch or commitid on unmatched page

### ISSUE THREAD

**Issue by jim-wilson** [carlosedp/riscv-bringup#22]
Current verison of meta-sifive has u-boot patches for 2021.07 and hence does not work with your instructions which specify checking out u-boot 2021.01.  This would be clearer if you specified a meta-sifive branch or commitid.  See for instance the question at 
[https://forums.sifive.com/t/where-to-start-with-a-hobby-os/5031/14](url)
which I answer 3 messages later once I figured out what was wrong.

**Comment by drmpeg** [comment]
For Ubuntu, you have to add the lines:
```
	"fdt_high=0xffffffffffffffff\0" \
	"initrd_high=0xffffffffffffffff\0" \
```
to the CONFIG_EXTRA_ENV_SETTINGS #define in include/configs/sifive-unmatched.h

**Comment by carlosedp** [comment]
Thanks a lot @drmpeg ... it worked perfect.

Can't it be added to the u-boot patch? Doesn't it work with other distros as well?
