### ISSUE TITLE
UbuntuHippo-RISC-V.img not working

### ISSUE THREAD

**Issue by hychiang73** [carlosedp/riscv-bringup#24]
Hi there,

Thank you guys for providing such good resources! But I'm encountering a newbie problem and need you guys help, any advice welcome, thank you :) 

I downloaded the prebuilt SDcard image, flashed it by `dd` and plug the SDcard into SiFive Unmatched board, but nothing outputs including u-boot messages.

I can boot up the system with the default SDcard given by SiFive. So I bought a new SDcard (Samsung EVO Plus 32GB) to install the prebuild image that you guys provided. I don't do anything other than `dd` command.

So is there any steps I miss up or should check with? Thanks in advance!

Prebuilt SDcard image link:
https://github.com/carlosedp/riscv-bringup/releases/download/v1.0/UbuntuHippo-RISC-V.img.gz

dd command:
`sudo dd if=UbuntuHippo-RISC-V.img of=/dev/sdc bs=64k iflag=fullblock oflag=direct conv=fsync status=progress`

**Comment by diglos** [comment]
Hi.

Didn't work for me either. However, building from scratch (OpenSBI+U-Boot+Kernel+Image) did. The only problem was the rootfs as the Hippo one is not available, but there are instructions to create it as well.

**Comment by hychiang73** [comment]
Hi diglos,

Thank you for the reply.

How would you build Hippo rootfs successfully? I was trying to build it from scratch and still failed because I don't have riscv64 environment while executing `sudo chroot temp-rootfs /bin/bash` (get Exec format error).

**Comment by hychiang73** [comment]
Hi,

I solved this problem. 

Apparently, the host must install Ubuntu Focal or newer before following the instructions. And the SDcard should use the one given by SiFive instead of other vendors.
