### ISSUE TITLE
Cannot start dockerd on Fedora image

### ISSUE THREAD

**Issue by zinovya** [carlosedp/riscv-bringup#3]
Hi,

  I was trying to run docker on Fedora QEMU image. I follow [this guide](https://github.com/carlosedp/riscv-bringup#building-go-on-your-risc-v-vm-or-sbc) get it going: 
 1. I've downloaded [pre build Fedora image] (https://drive.google.com/open?id=1N2ughbCAxaVTk5UT9tSucCFyoOnDlk4H)
 2. I have used `run_fedora.sh` script to launch the QEMU.
 3. Downloaded pre-build Go, [install pack] (https://drive.google.com/open?id=1Op8l6yq6H_C_zpZUpvO-zHxwbtcrAGcQ) and used `install.sh` to install docker.
  
  The install script reported an error when docker service (`systemctl start docker`) was launched:

> Job for docker.service failed because the control process exited with error code.
> See "systemctl status docker.service" and "journalctl -xe" for details.

  When I run `journalctl -xn | less` I can see following docker related messages:

```
Sep 05 06:37:19 fedora-riscv dockerd[4144]: time="2019-09-05T06:37:19.926035565-04:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Sep 05 06:37:19 fedora-riscv dockerd[4144]: time="2019-09-05T06:37:19.930419472-04:00" level=info msg="Loading containers: start."
Sep 05 06:37:20 fedora-riscv systemd[1]: Started Process Core Dump (PID 4161/UID 0).
Sep 05 06:38:12 fedora-riscv systemd-coredump[4162]: Cannot store coredump of 4158 (iptables): No space left on device
Sep 05 06:38:14 fedora-riscv systemd-coredump[4162]: Process 4158 (iptables) of user 0 dumped core.
-- Subject: Process 4158 (iptables) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 4158 (iptables) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
Sep 05 06:38:14 fedora-riscv dockerd[4144]: time="2019-09-05T06:38:14.389911084-04:00" level=warning msg="Running iptables --wait -t nat -L -n failed with message: `ERROR: 0 not a valid target)`, error: signal: aborted (core dumped)"
Sep 05 06:38:14 fedora-riscv systemd[1]: systemd-coredump@51-4161-0.service: Succeeded.
```

  I tried restarting QEMU, but the problem persists. When I perform the same steps on Debian image, it works fine.

  Any help much appreciated.

**Comment by carlosedp** [comment]
I'm rebuilding and updating the image. The problem was in the kernel. Will be up later today.

**Comment by carlosedp** [comment]
There it go... you can grab the updated Fedora image on https://drive.google.com/open?id=1MndnrABt3LUgEBVq-ZYWWzo1PVhxfOla.

The readme is updated too.

**Comment by zinovya** [comment]
@carlosedp, thanks a lot for prompt response

**Comment by carlosedp** [comment]
Please report back if it worked.

**Comment by zinovya** [comment]
@carlosedp I just tried it - works fine. Thanks again.
