### ISSUE TITLE
Need latest version of docker and kubernetes.

### ISSUE THREAD

**Issue by kconsul** [carlosedp/riscv-bringup#33]
Hi,

I am running riscv64 on qemu.

I tried both the docker as well as kubernetes for riscv (.deb files) you provided.
Docker installs and works fine when I upgrade glibc.

Kubernetes however shows issues due to kubelet not starting.
On checking journalctl I see that the issue is that the cgroups fs is not compatible with this
version of kubernetes. It probably needs a newer version of kubernetes.

Do you have a latest version of docker and kubernetes for riscv64 that I could install and run ?

Alternatively:
I cloned the latest kubernetes source code on my ubuntu riscv64 VM and then I compiled it
without using docker. It compiled separately.
kubeadm works fine but it expects the following riscv64 docker images to be present:
# kubeadm config images list
k8s.gcr.io/kube-controller-manager:v1.23.3
k8s.gcr.io/kube-scheduler:v1.23.3
k8s.gcr.io/kube-proxy:v1.23.3
k8s.gcr.io/pause:3.6
k8s.gcr.io/etcd:3.5.1-0
k8s.gcr.io/coredns/coredns:v1.8.6
# 

How can I create the above docker images from my compiled kubernetes build ?
I see that the binaries and directories for all those images are compiled and present for riscv64 in my
kubernetes build.

Thanks!

**Comment by carlosedp** [comment]
I haven't build the latest versions recently. There are guides and scripts here in the repo pointing on how to build them. Might need adjustments due to recent versions.

Refs:

* https://github.com/carlosedp/riscv-bringup/tree/master/kubernetes
* https://github.com/carlosedp/riscv-bringup/blob/master/kubernetes/build_images.sh
* https://github.com/carlosedp/riscv-bringup/blob/master/build-docker-env.md

**Comment by kconsul** [comment]
I'm having compilation and other issues building docker and kubernetes for the latest
versions.

Can you create the .deb files for docker and kubernetes for the latest versions ? 

I would much appreciate your help on this.

**Comment by carlosedp** [comment]
I can't do it right now. Might update the packages in the future tho.

**Comment by kconsul** [comment]
Hi,

I have been trying your build_images.sh script on my adm64 machine and
things mostly seem to go fine.
But, some of the docker RUN statements are failing because the binaries
inside the docker container
are riscv64 and they won't execute on my amd64 build server. Due to this my
etcd won't compile and will not
get uploaded to the docker hub website.

What is the way out for this ? I need to execute your build_image.sh script
on my amd64 build server because
my cross compiler and kubernetes build are there.

Thanks again.

**Comment by kconsul** [comment]
Hi,

I am now able to get the cluster up and running with kubeadm init as per
your web page.

Now, when I try to deploy flannel network I get:
***@***.***:~# kubectl apply -f
https://gist.github.com/carlosedp/337b99a98cdcf5962f4a0e24a778994c/raw/kube-flannel.yml

Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+,
unavailable in v1.25+
podsecuritypolicy.policy/psp.flannel.unprivileged configured
serviceaccount/flannel unchanged
configmap/kube-flannel-cfg unchanged
daemonset.apps/kube-flannel-ds-amd64 unchanged
daemonset.apps/kube-flannel-ds-arm64 unchanged
daemonset.apps/kube-flannel-ds-arm unchanged
daemonset.apps/kube-flannel-ds-ppc64le unchanged
daemonset.apps/kube-flannel-ds-s390x unchanged
daemonset.apps/kube-flannel-ds-riscv64 unchanged
unable to recognize "
https://gist.github.com/carlosedp/337b99a98cdcf5962f4a0e24a778994c/raw/kube-flannel.yml":
no matches for kind "ClusterRole" in version "
rbac.authorization.k8s.io/v1beta1"
unable to recognize "
https://gist.github.com/carlosedp/337b99a98cdcf5962f4a0e24a778994c/raw/kube-flannel.yml":
no matches for kind "ClusterRoleBinding" in version "
rbac.authorization.k8s.io/v1beta1"
***@***.***:~#

After that, when I try to get the pods:
***@***.***:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                             READY   STATUS
 RESTARTS      AGE
kube-system   coredns-7b978d84f6-4ptcx         0/1     ContainerCreating
0             14m
kube-system   coredns-7b978d84f6-9gpmx         0/1     ContainerCreating
0             14m
kube-system   etcd-ubuntu                      1/1     Running
50            15m
kube-system   kube-apiserver-ubuntu            1/1     Running
23            15m
kube-system   kube-controller-manager-ubuntu   1/1     Running
6             16m

*kube-system   kube-flannel-ds-riscv64-wtghs    0/1     CrashLoopBackOff
 4 (75s ago)   12m*kube-system   kube-proxy-zlvmn                 1/1
Running             0             14m
kube-system   kube-scheduler-ubuntu            1/1     Running
10            15m
***@***.***:~#

When I look at the docker logs of the flannel container I get:
***@***.***:~# docker logs 628652fdcc8c
I0223 06:12:54.411328       1 main.go:518] Determining IP address of
default interface
I0223 06:12:54.714273       1 main.go:531] Using interface with name eth1
and address 10.0.2.15
I0223 06:12:54.716293       1 main.go:548] Defaulting external address to
interface address (10.0.2.15)
W0223 06:12:54.717399       1 client_config.go:517] Neither --kubeconfig
nor --master was specified.  Using the inClusterConfig.  This might not
work.

*E0223 06:12:59.311993       1 main.go:243] Failed to create SubnetManager:
error retrieving pod spec for 'kube-system/kube-flannel-ds-riscv64-wtghs':
pods "kube-flannel-ds-riscv64-wtghs" is forbidden: User
"system:serviceaccount:kube-system:flannel" cannot get resource "pods" in
API group "" in the namespace ***@***.***:~#

Can you please tell me how to successfully deploy the flannel network ? At
least a few steps would be much appreciated by me.

Thanks and Regards.

**Comment by kconsul** [comment]
Also, there are 2 coredns pods that seem to be in ContainerCreating and not
Running state.
I think I will need your help on this one too.

**Comment by kconsul** [comment]
One more thing.. I have compiled v1.23.0 kubernetes binaries. You might
need this info from my side.

Thanks again.

**Comment by kconsul** [comment]
Ok, I could finally create flannel network by creating the
/run/flannel/subnet.env file and I get now the following
output:
***@***.***:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                             READY   STATUS    RESTARTS
AGE
kube-system   coredns-7b978d84f6-99mm5         1/1     Running   0
 5m18s
kube-system   coredns-7b978d84f6-g6wtm         1/1     Running   0
 5m17s
kube-system   etcd-ubuntu                      1/1     Running   52
5m29s
kube-system   kube-apiserver-ubuntu            1/1     Running   25
6m6s
kube-system   kube-controller-manager-ubuntu   1/1     Running   6
 5m29s
kube-system   kube-flannel-ds-riscv64-84df6    1/1     Running   0
 46s
kube-system   kube-proxy-jzwcn                 1/1     Running   0
 5m20s
kube-system   kube-scheduler-ubuntu            1/1     Running   12
6m32s
***@***.***:~# kubectl taint nodes --all node-role.kubernetes.io/master-
node/ubuntu untainted

It's all running fine now. Thanks all the same!

Regards.
