### ISSUE TITLE
[Feature] carlosedp/golang docker images for 1.18

### ISSUE THREAD

**Issue by olof-nord** [carlosedp/riscv-bringup#45]
Hello @carlosedp!

With some projects starting to use Golang 1.18, what do you think about building and pushing a `carlosedp/golang:1.18` docker image?

Following the official golang docker decision to not support riscv until Debian does, from what I can tell this is the most official alternative.

https://github.com/docker-library/golang/issues/435

Really appreciating your work!

**Comment by carlosedp** [comment]
I'm working on a Docker image with multi-stage build to address this.
Give me a couple hours to make it work and I'll let you know.
Thanks for pointing this out Olof.

**Comment by carlosedp** [comment]
There it goes... pushed new images to https://hub.docker.com/r/carlosedp/golang/tags and Go RISC-V tarballs to https://github.com/carlosedp/riscv-bringup/releases/tag/v1.0.

Also the updated Dockerfiles allow to build the tarball and the images. Check https://github.com/carlosedp/riscv-bringup/commit/548b1de5a06c240f8c7dbe59959ecf35b53e5450

**Comment by carlosedp** [comment]
Let me know if we can close this

**Comment by olof-nord** [comment]
amazing!
