### ISSUE TITLE
No output from the Ubuntu Focal image

### ISSUE THREAD

**Issue by tommythorn** [carlosedp/riscv-bringup#6]
OS: Ubuntu 19.10 64-bit (up to date)
Host: Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz
Qemu: QEMU emulator version 4.0.0 (Debian 1:4.0+dfsg-0ubuntu9.4)

```
$ wget https://github.com/carlosedp/riscv-bringup/releases/download/v1.0/UbuntuFocal-riscv64-QemuVM.tar.gz
$ tar xvzf UbuntuFocal-riscv64-QemuVM.tar.gz
$ ./run_riscvVM.sh 
```

After which I see the expected qemu four processes but no output(!) and no socket connection, even after more than an hour.  Since I can see the fw is openSBI I usually get a lot of console output so this is unexpected.

**Comment by tommythorn** [comment]
PS: host has 32 GiB of ram and plenty of disk space

**Comment by tommythorn** [comment]
Oh, I went with the instructions on Twitter and didn't notice the need to patch Qemu.  I'll close when I can confirm that this is the fix.

**Comment by carlosedp** [comment]
Nice you figured it out. I use Qemu 4.2.50 on Mac and works fine.
For the record, I think it's better to build Qemu from source on Linux since most distros have pretty old versions.
