### ISSUE TITLE
Update opensbi generic platform for qemu build instructions

### ISSUE THREAD

**Issue by atishp04** [carlosedp/riscv-bringup#7]
OpenSBI currently supports FDT based generic platform. As a result, qemu/virt platform is removed in favor of generic platform. I think the document should updated here as it says to pull master opensbi.

Generic platform support
http://lists.infradead.org/pipermail/opensbi/2020-April/001998.html

Qemu platform support removal
http://lists.infradead.org/pipermail/opensbi/2020-May/002042.html

**Comment by et-tommythorn** [comment]
Awesome.  That will increase the chance of booting this in Dromajo (the current fw image has a lot of U540 assumptions).

**Comment by carlosedp** [comment]
In the [Qemu guide](https://github.com/carlosedp/riscv-bringup/blob/master/Qemu/Readme.md#build-opensbi), I currently pull OpenSBI v0.6 that has compatibility with the current Kernel.

What requires changes is building OpenSBI, using:

```sh
make CROSS_COMPILE=riscv64-unknown-linux-gnu- \
     PLATFORM=generic \
     FW_PAYLOAD_PATH=../u-boot/u-boot.bin
```

Is it right?

**Comment by atishp04** [comment]
And the firmware path needs to be updated.
build/platform/generic/firmware/fw_payload.bin

**Comment by carlosedp** [comment]
ah yes.. nice! Gonna test this right now and update the guide:)
Thanks Atish

**Comment by atishp04** [comment]
Awesome. While a separate HiFive unleashed platform will continue to exist, you can also use the generic platform to boot HiFive Unleashed. So the same generic platform for binary should work on both Qemu and HiFive Unleashed!!

**Comment by atishp04** [comment]
> Awesome. That will increase the chance of booting this in Dromajo (the current fw image has a lot of U540 assumptions).

That's great. I took a quick look at the github repo for Dromajo and couldn't find OpenSBI changes.
Let me know if you see any issues with using the generic platform for Dromajo.

**Comment by et-tommythorn** [comment]
OT: I'm embarrassingly behind on upstreaming attempts, but they _are_
there:
https://github.com/chipsalliance/dromajo/blob/master/run/opensbi.dromajo.tar.gz

Note, this also supports the Esperanto Technology Maxion core.

I'd be happy to open an openSBI issue in the Dromajo and continue the
conversation there about
what needs changing.

**Comment by carlosedp** [comment]
Confirming that OpenSBI from master (OpenSBI v0.7-31-gd626037) + U-Boot v2020.04 and Kernel 5.7-rc3 boots perfectly and all CPUs are detected. With v0.7 the generic platform is still not available.

With Kernel 5.6, only one CPU is detected with this OpenSBI version.

**Comment by et-tommythorn** [comment]
OT again (so sorry): Note, I took out all the device models, but I plan to
put enough back that we can at least run Ubuntu.

**Comment by atishp04** [comment]
> With Kernel 5.6, only one CPU is detected with this OpenSBI version.

That is expected. As the OpenSBI readme says, you have to migrate to the latest kernel (5.7-rc+) if you are using OpenSBI v0.7 or higher. That's happened because of the HSM extension and ordered booting support added in 5.7-rc1 & OpenSBI v0.7

**Comment by carlosedp** [comment]
I'll keep this at hand and update the full guide once there is a new OpenSBI version (0.8) and Kernel 5.7 gets released :)

**Comment by atishp04** [comment]
> I'd be happy to open an openSBI issue in the Dromajo and continue the
Sure. I took a quick look at the sources and I don't expect any major changes as long as the the simulator provides a DT with correct MMIO addresses. You should be able to boot generic platform on the emulator.

**Comment by carlosedp** [comment]
Closing this as latest Unmatched guide uses Generic on OpenSBI
